---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: barisozdag/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: haddons-repo
      repository_edge: haddons-repo-edge
      repository_beta: haddons-repo-beta
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
